apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitops-app
  name: gitops-app
  namespace: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitops-app
        environment: dev
    spec:
      containers:
      - image: nginx
        name: gitops-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
