apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitops-app
  name: gitops-app
  namespace: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitops-app
        environment: dev
    spec:
      containers:
      - image: registry.gitlab.com/ignw1/products/cloud-strategy-programs/advanced-platforms-and-integrations/cn-gitops-app:v1.0.11
        name: gitops-app
        ports:
        - containerPort: 8000
        resources: {}
      imagePullSecrets:
      - name: gitlab-credentials
status: {}
