apiVersion: v1
kind: Service
metadata:
  name: gitops-app-service
  namespace: gitops
spec:
  selector:
    app: gitops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
